### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by joellejohnson** [gwct/referee#1]
Hello, 
I have tried running the input line for referee: 
`python referee.py -gl file.mpileup -ref ref.file.fasta --pileup`
First I received this error: 
  File "/work/jgjohns6/penicillata/referee/referee.py", line 10, in <module>                                                                                                        
    import sys, os, multiprocessing as mp, shutil, lib.refcore as RC, lib.ref_calc as CALC, \                                                                                       
  File "/work/jgjohns6/penicillata/referee/lib/ref_calc.py", line 210                                                                                                               
    print gt, log_gls[gt];                                                                                                                                                          
           ^                                                                                                                                                                        
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(gt, log_gls[gt])?

Then, after manually adding in the parentheses I received a similar one: 
Traceback (most recent call last):                                                                                                                                                  
  File "/work/jgjohns6/penicillata/referee/referee.py", line 10, in <module>                                                                                                        
    import sys, os, multiprocessing as mp, shutil, lib.refcore as RC, lib.ref_calc as CALC, \                                                                                       
  File "/work/jgjohns6/penicillata/referee/lib/ref_calc.py", line 211                                                                                                               
    print rq, lr, l_match, l_mismatch;                                                                                                                                              
           ^                                                                                                                                                                        
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(rq, lr, l_match, l_mismatch)? 

However even after going in and adding those parentheses, I received the following error: 
File "/work/jgjohns6/penicillata/referee/referee.py", line 10, in <module>
    import sys, os, multiprocessing as mp, shutil, lib.refcore as RC, lib.ref_calc as CALC, \                                                                                      
  File "/work/jgjohns6/penicillata/referee/lib/ref_calc.py", line 1, in <module>
    import math, re, refcore as RC, ref_out as OUT, sys
ModuleNotFoundError: No module named 'refcore'

I am not sure what is happening here, and why the program won't just run.

**Comment by joellejohnson** [comment]
Update: using python2, the program ran and produced options menu, but still produced this error: 
`  File "/work/jgjohns6/penicillata/referee/referee.py", line 99, in <module>
    referee(files, globs, step_start_time);
  File "/work/jgjohns6/penicillata/referee/referee.py", line 36, in referee
    result = CALC.refCalc((file_num, files[file_num], globs));
  File "/work/jgjohns6/penicillata/referee/lib/ref_calc.py", line 202, in refCalc
    outdict = { 'scaff' : scaff, 'pos' : pos, 'ref' : ref, 'rq' : rq, 'raw' : raw_score,
UnboundLocalError: local variable 'raw_score' referenced before assignment`

**Comment by gwct** [comment]
Hello,

Sorry about the print and module errors. They were apparently some lingering incompatibilities between python 2 and 3. I've pushed an update that should fix them, so you should be good to run in python 3 again. Let me know if its still not working. Thanks for bringing them to my attention!

As for the next error, `local variable 'raw_score' referenced before assignment`, I'm unable to replicate this with my own test data. Would you be able to send the input files you are using along with the exact command you've used to run the program? If so, you can either attach the files here or send me an email (grthomas [at] indiana.edu).

Thanks!
-Gregg

**Comment by gwct** [comment]
This issue was caused by some undefined variables when the pileup file outputs sites with 0 reads mapped (rather than just skipping them). The problem has been fixed!
