### ISSUE TITLE
TypeError: cannot pickle '_thread.RLock' object

### ISSUE THREAD

**Issue by richardstoeckl** [gwct/referee#8]
Hi,

I seem to be experiencing an error related to multiprocessing, however, the error also occurs when `-p 1` is set.
Any clue what might be the problem?

```bash
#
# =================================================
                   __                    
         _ __ ___ / _| ___ _ __ ___  ___ 
        | '__/ _ \ |_ / _ \ '__/ _ \/ _ \
        | | |  __/  _|  __/ | |  __/  __/
        |_|  \___|_|  \___|_|  \___|\___|
    Reference genome quality score calculator.

       Pseudo assembly by iterative mapping.

#
# Version 1.2 released on August 08, 2020
# Referee was developed by Gregg Thomas and Matthew Hahn
# Citation:      https://doi.org/10.1093/gbe/evz088
# Website:       https://gwct.github.io/referee/
# Report issues: https://github.com/gwct/referee/issues
#
# The date and time at the start is: 02.14.2023 | 10:26:14
# Using Python version:              3.9.15
#
# The program was called as: /home/rks/referee-1.2/referee.py -p 1 -gl results/BBR060303/referee/BBR060303.pileup -ref results/common/finalAssemblies/BBR060303_final.fasta -d results/BBR060303/referee/ -prefix BBR060303_referee_scores --pileup --correct --overwrite --mapq --quiet --haploid
#
# -----------------------------------------------------------------------------------------------------------------------------
# INPUT/OUTPUT INFO
# Input file:       results/BBR060303/referee/BBR060303.pileup
# Reference file:   results/common/finalAssemblies/BBR060303_final.fasta
# Output directory: results/BBR060303/referee/
# Output prefix:    BBR060303_referee_scores
# -----------------------------------------------------------------------------------------------------------------------------
# OPTIONS INFO
# Option            Current setting     Current action
# -----------------------------------------------------------------------------------------------------------------------------
# --pileup          True                Input type set to pileup. Referee will calculate genotype likelihoods.
# --mapq            True                Incorporating mapping qualities (7th column of pileup file) into quality score calculations if they are present.
# --fastq           False               Not writing output in FASTQ format.
# --bed             False               Not writing output in BED format.
# --mapped          False               Calculating scores for every position in the reference genome.
# --haploid         True                Calculating genotype likelihoods and quality scores for HAPLOID data (4 genotypes).
# --raw             False               NOT printing raw Referee score in tabbed output.
# --correct         True                Suggesting higher scoring alternative base when reference score is negative or reference base is N.
# --quiet           True                No further information will be output while Referee is running.
# -p                1                   Referee will use this many processes to run.
# -l                100000              This many lines will be read per process to be calculated at one time in parallel
# -----------------------------------------------------------------------------------------------------------------------------
# Running...
# 02.14.2023  10:26:14  Detecting compression                   In progress...                Success!                      0.01172             8e-05           14.72656                 22.28906            
# 02.14.2023  10:26:14  Indexing reference FASTA                In progress...                Success!                      0.01654             0.00473         14.72656                 22.28906            
# 02.14.2023  10:26:14  Getting scaffold lengths from index     In progress...                Success! Read 1 scaffolds     0.01669             4e-05           14.72656                 22.28906            
# 02.14.2023  10:26:14  Computing likelihood look-up table      In progress...                Success!                      0.02417             0.00741         17.52344                 24.84766            
# 02.14.2023  10:26:14  Processing lines 1-100000               In progress...                Traceback (most recent call last):
  File "/home/rks/referee-1.2/referee.py", line 166, in <module>
    referee(globs);
  File "/home/rks/referee-1.2/referee.py", line 88, in referee
    for result in pool.starmap(CALC.refCalc, ((line_chunk, globs) for line_chunk in line_chunks)):
  File "/home/rks/miniconda3/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/rks/miniconda3/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/rks/miniconda3/lib/python3.9/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/home/rks/miniconda3/lib/python3.9/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/rks/miniconda3/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_thread.RLock' object
```

Best,
Richard

**Comment by gwct** [comment]
Hi Richard,
Unfortunately I can't see anything clear in the error message its giving in the log file. Would it be possible for you to send a small snippet of your data so that I can try reproducing this error?
Thanks,
-Gregg

**Comment by richardstoeckl** [comment]
Hi Gregg,
while trying to get a small enough dataset to be able to send it to you, I noticed that I could get referee to work by simply changing to a conda environment which I set up for a different purpose. I used the same command/files/paths/params, the only change was the conda env. 
I attached the output of `conda list > file.txt` of the base environment (with which I got the error) and the conda env that worked.

I will try some more environments to maybe find out what exactly is the important difference.
Kind regards,
Richard

[referee_doesnt_work_in_this_conda_env.txt](https://github.com/gwct/referee/files/10755474/referee_doesnt_work_in_this_conda_env.txt)
[referee_works_in_this_conda_env.txt](https://github.com/gwct/referee/files/10755475/referee_works_in_this_conda_env.txt)

**Comment by richardstoeckl** [comment]
So it's not the python version. Both a "clean" environment with just `python==3.8.15`, as well as just `python==3.9.15` work fine.

**Comment by gwct** [comment]
Hmm, that's pretty strange. Since there aren't any external dependencies for Referee my first guess would have been the Python version. But since that isn't the case I'm thinking that the `multiprocessing` module is importing some other package that differs between the two environments. This seems consistent with at least some of what I'm reading when I search for this error. Unfortunately this makes the source of this error really hard to track down. Do you need Referee to run in that specific environment or are you able to use it the one in which it works?

**Comment by richardstoeckl** [comment]
So I have tried some more envs, but as you said, finding the source is very difficult. I don't need referee to work in that one specific env so I will close this issue. Thank you for your help!
